//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace View.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of View.DtoClasses.BaseView from the entity model.</summary>
	public static partial class BaseViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Restaurant.EntityClasses.BaseEntity, View.DtoClasses.BaseView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Restaurant.EntityClasses.BaseEntity, View.DtoClasses.BaseView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static BaseViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to View.DtoClasses.BaseView which instances are projected from the 
		/// results of the specified baseQuery, which returns Restaurant.EntityClasses.BaseEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve View.DtoClasses.BaseView instances</returns>
		public static IQueryable<View.DtoClasses.BaseView> ProjectToBaseView(this IQueryable<Restaurant.EntityClasses.BaseEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to View.DtoClasses.BaseView which instances are projected from the
		/// Restaurant.EntityClasses.BaseEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Restaurant.EntityClasses.BaseEntity instance created from the specified entity instance</returns>
		public static View.DtoClasses.BaseView ProjectToBaseView(this Restaurant.EntityClasses.BaseEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<Restaurant.EntityClasses.BaseEntity, View.DtoClasses.BaseView>> CreateProjectionFunc()
		{
			return p__0 => new View.DtoClasses.BaseView()
			{
				Option = p__0.Option,
				Price = p__0.Price,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_BaseView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

