//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace View.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of View.DtoClasses.OrderView from the entity model.</summary>
	public static partial class OrderViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Restaurant.EntityClasses.OrderEntity, View.DtoClasses.OrderView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Restaurant.EntityClasses.OrderEntity, View.DtoClasses.OrderView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static OrderViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to View.DtoClasses.OrderView which instances are projected from the 
		/// results of the specified baseQuery, which returns Restaurant.EntityClasses.OrderEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve View.DtoClasses.OrderView instances</returns>
		public static IQueryable<View.DtoClasses.OrderView> ProjectToOrderView(this IQueryable<Restaurant.EntityClasses.OrderEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to View.DtoClasses.OrderView which instances are projected from the
		/// Restaurant.EntityClasses.OrderEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Restaurant.EntityClasses.OrderEntity instance created from the specified entity instance</returns>
		public static View.DtoClasses.OrderView ProjectToOrderView(this Restaurant.EntityClasses.OrderEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<Restaurant.EntityClasses.OrderEntity, View.DtoClasses.OrderView>> CreateProjectionFunc()
		{
			return p__0 => new View.DtoClasses.OrderView()
			{
				CustomerName = p__0.CustomerName,
				Id = p__0.Id,
				Pizzas = p__0.Pizzas.Select(p__1 => new View.DtoClasses.OrderViewTypes.Pizza()
				{
					Base = p__1.Base,
					Dough = p__1.Dough,
					Id = p__1.Id,
					PizzaToppings = p__1.PizzaToppings.Select(p__2 => new View.DtoClasses.OrderViewTypes.PizzaTypes.PizzaTopping()
					{
						Topping = p__2.Topping,
					}).ToList(),
					Size = p__1.Size,
				}).ToList(),
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_OrderView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

