//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace View.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of View.DtoClasses.PizzaToppingView from the entity model.</summary>
	public static partial class PizzaToppingViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Restaurant.EntityClasses.PizzaToppingEntity, View.DtoClasses.PizzaToppingView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Restaurant.EntityClasses.PizzaToppingEntity, View.DtoClasses.PizzaToppingView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static PizzaToppingViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to View.DtoClasses.PizzaToppingView which instances are projected from the 
		/// results of the specified baseQuery, which returns Restaurant.EntityClasses.PizzaToppingEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve View.DtoClasses.PizzaToppingView instances</returns>
		public static IQueryable<View.DtoClasses.PizzaToppingView> ProjectToPizzaToppingView(this IQueryable<Restaurant.EntityClasses.PizzaToppingEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to View.DtoClasses.PizzaToppingView which instances are projected from the
		/// Restaurant.EntityClasses.PizzaToppingEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Restaurant.EntityClasses.PizzaToppingEntity instance created from the specified entity instance</returns>
		public static View.DtoClasses.PizzaToppingView ProjectToPizzaToppingView(this Restaurant.EntityClasses.PizzaToppingEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<Restaurant.EntityClasses.PizzaToppingEntity, View.DtoClasses.PizzaToppingView>> CreateProjectionFunc()
		{
			return p__0 => new View.DtoClasses.PizzaToppingView()
			{
				PizzaId = p__0.PizzaId,
				Topping = p__0.Topping,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_PizzaToppingView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

