//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace View.Persistence
{
	/// <summary>Static class for (extension) methods for fetching and projecting instances of View.DtoClasses.SizeView from the entity model.</summary>
	public static partial class SizeViewPersistence
	{
		private static readonly System.Linq.Expressions.Expression<Func<Restaurant.EntityClasses.SizeEntity, View.DtoClasses.SizeView>> _projectorExpression = CreateProjectionFunc();
		private static readonly Func<Restaurant.EntityClasses.SizeEntity, View.DtoClasses.SizeView> _compiledProjector = CreateProjectionFunc().Compile();
	
		/// <summary>Empty static ctor for triggering initialization of static members in a thread-safe manner</summary>
		static SizeViewPersistence() { }
	
		/// <summary>Extension method which produces a projection to View.DtoClasses.SizeView which instances are projected from the 
		/// results of the specified baseQuery, which returns Restaurant.EntityClasses.SizeEntity instances, the root entity of the derived element returned by this query.</summary>
		/// <param name="baseQuery">The base query to project the derived element instances from.</param>
		/// <returns>IQueryable to retrieve View.DtoClasses.SizeView instances</returns>
		public static IQueryable<View.DtoClasses.SizeView> ProjectToSizeView(this IQueryable<Restaurant.EntityClasses.SizeEntity> baseQuery)
		{
			return baseQuery.Select(_projectorExpression);
		}
		
		/// <summary>Extension method which produces a projection to View.DtoClasses.SizeView which instances are projected from the
		/// Restaurant.EntityClasses.SizeEntity entity instance specified, the root entity of the derived element returned by this method.</summary>
		/// <param name="entity">The entity to project from.</param>
		/// <returns>Restaurant.EntityClasses.SizeEntity instance created from the specified entity instance</returns>
		public static View.DtoClasses.SizeView ProjectToSizeView(this Restaurant.EntityClasses.SizeEntity entity)
		{
			return _compiledProjector(entity);
		}
		
		private static System.Linq.Expressions.Expression<Func<Restaurant.EntityClasses.SizeEntity, View.DtoClasses.SizeView>> CreateProjectionFunc()
		{
			return p__0 => new View.DtoClasses.SizeView()
			{
				Multiplier = p__0.Multiplier,
				Option = p__0.Option,
	// __LLBLGENPRO_USER_CODE_REGION_START ProjectionRegion_SizeView 
	// __LLBLGENPRO_USER_CODE_REGION_END 
			};
		}
	}
}

