//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
////////////////////////////////////////////////////////////// 
using System;
using System.Linq;
using Restaurant.EntityClasses;
using Restaurant.HelperClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;
using SD.LLBLGen.Pro.QuerySpec.AdapterSpecific;
using SD.LLBLGen.Pro.QuerySpec;

namespace Restaurant.FactoryClasses
{
	/// <summary>Factory class to produce DynamicQuery instances and EntityQuery instances</summary>
	public partial class QueryFactory : QueryFactoryBase2
	{
		/// <summary>Creates and returns a new EntityQuery for the Base entity</summary>
		public EntityQuery<BaseEntity> Base { get { return Create<BaseEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Dough entity</summary>
		public EntityQuery<DoughEntity> Dough { get { return Create<DoughEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Order entity</summary>
		public EntityQuery<OrderEntity> Order { get { return Create<OrderEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Pizza entity</summary>
		public EntityQuery<PizzaEntity> Pizza { get { return Create<PizzaEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the PizzaTopping entity</summary>
		public EntityQuery<PizzaToppingEntity> PizzaTopping { get { return Create<PizzaToppingEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Size entity</summary>
		public EntityQuery<SizeEntity> Size { get { return Create<SizeEntity>(); } }

		/// <summary>Creates and returns a new EntityQuery for the Topping entity</summary>
		public EntityQuery<ToppingEntity> Topping { get { return Create<ToppingEntity>(); } }

		/// <inheritdoc/>
		protected override IElementCreatorCore CreateElementCreator() { return new ElementCreator(); }
 
	}
}