//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using Restaurant.HelperClasses;
using Restaurant.FactoryClasses;
using Restaurant.RelationClasses;

using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Restaurant.EntityClasses
{
	// __LLBLGENPRO_USER_CODE_REGION_START AdditionalNamespaces
	// __LLBLGENPRO_USER_CODE_REGION_END

	/// <summary>Entity class which represents the entity 'Size'.<br/><br/></summary>
	[Serializable]
	public partial class SizeEntity : CommonEntityBase
		// __LLBLGENPRO_USER_CODE_REGION_START AdditionalInterfaces
		// __LLBLGENPRO_USER_CODE_REGION_END
	
	{
		private EntityCollection<PizzaEntity> _pizzas;
		// __LLBLGENPRO_USER_CODE_REGION_START PrivateMembers
		// __LLBLGENPRO_USER_CODE_REGION_END

		private static SizeEntityStaticMetaData _staticMetaData = new SizeEntityStaticMetaData();
		private static SizeRelations _relationsFactory = new SizeRelations();

		/// <summary>All names of fields mapped onto a relation. Usable for in-memory filtering</summary>
		public static partial class MemberNames
		{
			/// <summary>Member name Pizzas</summary>
			public static readonly string Pizzas = "Pizzas";
		}

		/// <summary>Static meta-data storage for navigator related information</summary>
		protected class SizeEntityStaticMetaData : EntityStaticMetaDataBase
		{
			public SizeEntityStaticMetaData()
			{
				SetEntityCoreInfo("SizeEntity", InheritanceHierarchyType.None, false, (int)Restaurant.EntityType.SizeEntity, typeof(SizeEntity), typeof(SizeEntityFactory), false);
				AddNavigatorMetaData<SizeEntity, EntityCollection<PizzaEntity>>("Pizzas", a => a._pizzas, (a, b) => a._pizzas = b, a => a.Pizzas, () => new SizeRelations().PizzaEntityUsingSize, typeof(PizzaEntity), (int)Restaurant.EntityType.PizzaEntity);
			}
		}

		/// <summary>Static ctor</summary>
		static SizeEntity()
		{
		}

		/// <summary> CTor</summary>
		public SizeEntity()
		{
			InitClassEmpty(null, null);
		}

		/// <summary> CTor</summary>
		/// <param name="fields">Fields object to set as the fields for this entity.</param>
		public SizeEntity(IEntityFields2 fields)
		{
			InitClassEmpty(null, fields);
		}

		/// <summary> CTor</summary>
		/// <param name="validator">The custom validator object for this SizeEntity</param>
		public SizeEntity(IValidator validator)
		{
			InitClassEmpty(validator, null);
		}

		/// <summary> CTor</summary>
		/// <param name="option">PK value for Size which data should be fetched into this Size object</param>
		public SizeEntity(System.String option) : this(option, null)
		{
		}

		/// <summary> CTor</summary>
		/// <param name="option">PK value for Size which data should be fetched into this Size object</param>
		/// <param name="validator">The custom validator object for this SizeEntity</param>
		public SizeEntity(System.String option, IValidator validator)
		{
			InitClassEmpty(validator, null);
			this.Option = option;
		}

		/// <summary>Private CTor for deserialization</summary>
		/// <param name="info"></param>
		/// <param name="context"></param>
		protected SizeEntity(SerializationInfo info, StreamingContext context) : base(info, context)
		{
			// __LLBLGENPRO_USER_CODE_REGION_START DeserializationConstructor
			// __LLBLGENPRO_USER_CODE_REGION_END
		}

		/// <summary>Creates a new IRelationPredicateBucket object which contains the predicate expression and relation collection to fetch the related entities of type 'Pizza' to this entity.</summary>
		/// <returns></returns>
		public virtual IRelationPredicateBucket GetRelationInfoPizzas() { return CreateRelationInfoForNavigator("Pizzas"); }
		
		/// <inheritdoc/>
		protected override EntityStaticMetaDataBase GetEntityStaticMetaData() {	return _staticMetaData; }

		/// <summary>Initializes the class members</summary>
		private void InitClassMembers()
		{
			PerformDependencyInjection();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassMembers
			// __LLBLGENPRO_USER_CODE_REGION_END

			OnInitClassMembersComplete();
		}

		/// <summary>Initializes the class with empty data, as if it is a new Entity.</summary>
		/// <param name="validator">The validator object for this SizeEntity</param>
		/// <param name="fields">Fields of this entity</param>
		private void InitClassEmpty(IValidator validator, IEntityFields2 fields)
		{
			OnInitializing();
			this.Fields = fields ?? CreateFields();
			this.Validator = validator;
			InitClassMembers();
			// __LLBLGENPRO_USER_CODE_REGION_START InitClassEmpty
			// __LLBLGENPRO_USER_CODE_REGION_END


			OnInitialized();
		}

		/// <summary>The relations object holding all relations of this entity with other entity classes.</summary>
		public static SizeRelations Relations { get { return _relationsFactory; } }

		/// <summary>Creates a new PrefetchPathElement2 object which contains all the information to prefetch the related entities of type 'Pizza' for this entity.</summary>
		/// <returns>Ready to use IPrefetchPathElement2 implementation.</returns>
		public static IPrefetchPathElement2 PrefetchPathPizzas { get { return _staticMetaData.GetPrefetchPathElement("Pizzas", CommonEntityBase.CreateEntityCollection<PizzaEntity>()); } }

		/// <summary>The Multiplier property of the Entity Size<br/><br/></summary>
		/// <remarks>Mapped on  table field: "size"."multiplier".<br/>Table field type characteristics (type, precision, scale, length): Real, 24, 0, 0.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, false, false</remarks>
		public virtual System.Single Multiplier
		{
			get { return (System.Single)GetValue((int)SizeFieldIndex.Multiplier, true); }
			set	{ SetValue((int)SizeFieldIndex.Multiplier, value); }
		}

		/// <summary>The Option property of the Entity Size<br/><br/></summary>
		/// <remarks>Mapped on  table field: "size"."option".<br/>Table field type characteristics (type, precision, scale, length): Text, 0, 0, 1073741824.<br/>Table field behavior characteristics (is nullable, is PK, is identity): false, true, false</remarks>
		public virtual System.String Option
		{
			get { return (System.String)GetValue((int)SizeFieldIndex.Option, true); }
			set	{ SetValue((int)SizeFieldIndex.Option, value); }
		}

		/// <summary>Gets the EntityCollection with the related entities of type 'PizzaEntity' which are related to this entity via a relation of type '1:n'. If the EntityCollection hasn't been fetched yet, the collection returned will be empty.<br/><br/></summary>
		[TypeContainedAttribute(typeof(PizzaEntity))]
		public virtual EntityCollection<PizzaEntity> Pizzas { get { return GetOrCreateEntityCollection<PizzaEntity, PizzaEntityFactory>("Size1", true, false, ref _pizzas); } }
		// __LLBLGENPRO_USER_CODE_REGION_START CustomEntityCode
		// __LLBLGENPRO_USER_CODE_REGION_END


	}
}

namespace Restaurant
{
	public enum SizeFieldIndex
	{
		///<summary>Multiplier. </summary>
		Multiplier,
		///<summary>Option. </summary>
		Option,
		/// <summary></summary>
		AmountOfFields
	}
}

namespace Restaurant.RelationClasses
{
	/// <summary>Implements the relations factory for the entity: Size. </summary>
	public partial class SizeRelations: RelationFactory
	{
		/// <summary>Returns a new IEntityRelation object, between SizeEntity and PizzaEntity over the 1:n relation they have, using the relation between the fields: Size.Option - Pizza.Size</summary>
		public virtual IEntityRelation PizzaEntityUsingSize
		{
			get { return ModelInfoProviderSingleton.GetInstance().CreateRelation(RelationType.OneToMany, "Pizzas", true, new[] { SizeFields.Option, PizzaFields.Size }); }
		}

	}
	
	/// <summary>Static class which is used for providing relationship instances which are re-used internally for syncing</summary>
	internal static class StaticSizeRelations
	{
		internal static readonly IEntityRelation PizzaEntityUsingSizeStatic = new SizeRelations().PizzaEntityUsingSize;

		/// <summary>CTor</summary>
		static StaticSizeRelations() { }
	}
}
