//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Restaurant.HelperClasses
{
	/// <summary>Field Creation Class for entity BaseEntity</summary>
	public partial class BaseFields
	{
		/// <summary>Creates a new BaseEntity.Option field instance</summary>
		public static EntityField2 Option { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BaseFieldIndex.Option); }}
		/// <summary>Creates a new BaseEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(BaseFieldIndex.Price); }}
	}

	/// <summary>Field Creation Class for entity DoughEntity</summary>
	public partial class DoughFields
	{
		/// <summary>Creates a new DoughEntity.Option field instance</summary>
		public static EntityField2 Option { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DoughFieldIndex.Option); }}
		/// <summary>Creates a new DoughEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(DoughFieldIndex.Price); }}
	}

	/// <summary>Field Creation Class for entity OrderEntity</summary>
	public partial class OrderFields
	{
		/// <summary>Creates a new OrderEntity.CustomerName field instance</summary>
		public static EntityField2 CustomerName { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.CustomerName); }}
		/// <summary>Creates a new OrderEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(OrderFieldIndex.Id); }}
	}

	/// <summary>Field Creation Class for entity PizzaEntity</summary>
	public partial class PizzaFields
	{
		/// <summary>Creates a new PizzaEntity.Base field instance</summary>
		public static EntityField2 Base { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaFieldIndex.Base); }}
		/// <summary>Creates a new PizzaEntity.Dough field instance</summary>
		public static EntityField2 Dough { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaFieldIndex.Dough); }}
		/// <summary>Creates a new PizzaEntity.Id field instance</summary>
		public static EntityField2 Id { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaFieldIndex.Id); }}
		/// <summary>Creates a new PizzaEntity.OrderId field instance</summary>
		public static EntityField2 OrderId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaFieldIndex.OrderId); }}
		/// <summary>Creates a new PizzaEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaFieldIndex.Price); }}
		/// <summary>Creates a new PizzaEntity.Size field instance</summary>
		public static EntityField2 Size { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaFieldIndex.Size); }}
	}

	/// <summary>Field Creation Class for entity PizzaToppingEntity</summary>
	public partial class PizzaToppingFields
	{
		/// <summary>Creates a new PizzaToppingEntity.PizzaId field instance</summary>
		public static EntityField2 PizzaId { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaToppingFieldIndex.PizzaId); }}
		/// <summary>Creates a new PizzaToppingEntity.Topping field instance</summary>
		public static EntityField2 Topping { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(PizzaToppingFieldIndex.Topping); }}
	}

	/// <summary>Field Creation Class for entity SizeEntity</summary>
	public partial class SizeFields
	{
		/// <summary>Creates a new SizeEntity.Multiplier field instance</summary>
		public static EntityField2 Multiplier { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SizeFieldIndex.Multiplier); }}
		/// <summary>Creates a new SizeEntity.Option field instance</summary>
		public static EntityField2 Option { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(SizeFieldIndex.Option); }}
	}

	/// <summary>Field Creation Class for entity ToppingEntity</summary>
	public partial class ToppingFields
	{
		/// <summary>Creates a new ToppingEntity.Option field instance</summary>
		public static EntityField2 Option { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ToppingFieldIndex.Option); }}
		/// <summary>Creates a new ToppingEntity.Price field instance</summary>
		public static EntityField2 Price { get { return ModelInfoProviderSingleton.GetInstance().CreateField2(ToppingFieldIndex.Price); }}
	}
	

}