//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using Restaurant.FactoryClasses;
using Restaurant.RelationClasses;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Restaurant.HelperClasses
{
	/// <summary>Singleton implementation of the ModelInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	public static class ModelInfoProviderSingleton
	{
		private static readonly IModelInfoProvider _providerInstance = new ModelInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static ModelInfoProviderSingleton()	{ }

		/// <summary>Gets the singleton instance of the ModelInfoProviderCore</summary>
		/// <returns>Instance of the FieldInfoProvider.</returns>
		public static IModelInfoProvider GetInstance()
		{
			return _providerInstance;
		}
	}

	/// <summary>Actual implementation of the ModelInfoProvider.</summary>
	internal class ModelInfoProviderCore : ModelInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="ModelInfoProviderCore"/> class.</summary>
		internal ModelInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores.</summary>
		private void Init()
		{
			this.InitClass();
			InitBaseEntityInfo();
			InitDoughEntityInfo();
			InitOrderEntityInfo();
			InitPizzaEntityInfo();
			InitPizzaToppingEntityInfo();
			InitSizeEntityInfo();
			InitToppingEntityInfo();
			this.BuildInternalStructures();
		}

		/// <summary>Inits BaseEntity's info objects</summary>
		private void InitBaseEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(BaseFieldIndex), "BaseEntity");
			this.AddElementFieldInfo("BaseEntity", "Option", typeof(System.String), true, false, false, false,  (int)BaseFieldIndex.Option, 1073741824, 0, 0);
			this.AddElementFieldInfo("BaseEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)BaseFieldIndex.Price, 0, 0, 0);
		}

		/// <summary>Inits DoughEntity's info objects</summary>
		private void InitDoughEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(DoughFieldIndex), "DoughEntity");
			this.AddElementFieldInfo("DoughEntity", "Option", typeof(System.String), true, false, false, false,  (int)DoughFieldIndex.Option, 1073741824, 0, 0);
			this.AddElementFieldInfo("DoughEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)DoughFieldIndex.Price, 0, 0, 0);
		}

		/// <summary>Inits OrderEntity's info objects</summary>
		private void InitOrderEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(OrderFieldIndex), "OrderEntity");
			this.AddElementFieldInfo("OrderEntity", "CustomerName", typeof(System.String), false, false, false, true,  (int)OrderFieldIndex.CustomerName, 1073741824, 0, 0);
			this.AddElementFieldInfo("OrderEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)OrderFieldIndex.Id, 0, 0, 10);
		}

		/// <summary>Inits PizzaEntity's info objects</summary>
		private void InitPizzaEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PizzaFieldIndex), "PizzaEntity");
			this.AddElementFieldInfo("PizzaEntity", "Base", typeof(System.String), false, true, false, false,  (int)PizzaFieldIndex.Base, 1073741824, 0, 0);
			this.AddElementFieldInfo("PizzaEntity", "Dough", typeof(System.String), false, true, false, false,  (int)PizzaFieldIndex.Dough, 1073741824, 0, 0);
			this.AddElementFieldInfo("PizzaEntity", "Id", typeof(System.Int32), true, false, true, false,  (int)PizzaFieldIndex.Id, 0, 0, 10);
			this.AddElementFieldInfo("PizzaEntity", "OrderId", typeof(System.Int32), false, true, false, false,  (int)PizzaFieldIndex.OrderId, 0, 0, 10);
			this.AddElementFieldInfo("PizzaEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)PizzaFieldIndex.Price, 0, 0, 0);
			this.AddElementFieldInfo("PizzaEntity", "Size", typeof(System.String), false, true, false, false,  (int)PizzaFieldIndex.Size, 1073741824, 0, 0);
		}

		/// <summary>Inits PizzaToppingEntity's info objects</summary>
		private void InitPizzaToppingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(PizzaToppingFieldIndex), "PizzaToppingEntity");
			this.AddElementFieldInfo("PizzaToppingEntity", "PizzaId", typeof(System.Int32), true, true, false, false,  (int)PizzaToppingFieldIndex.PizzaId, 0, 0, 10);
			this.AddElementFieldInfo("PizzaToppingEntity", "Topping", typeof(System.String), true, true, false, false,  (int)PizzaToppingFieldIndex.Topping, 1073741824, 0, 0);
		}

		/// <summary>Inits SizeEntity's info objects</summary>
		private void InitSizeEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(SizeFieldIndex), "SizeEntity");
			this.AddElementFieldInfo("SizeEntity", "Multiplier", typeof(System.Single), false, false, false, false,  (int)SizeFieldIndex.Multiplier, 0, 0, 24);
			this.AddElementFieldInfo("SizeEntity", "Option", typeof(System.String), true, false, false, false,  (int)SizeFieldIndex.Option, 1073741824, 0, 0);
		}

		/// <summary>Inits ToppingEntity's info objects</summary>
		private void InitToppingEntityInfo()
		{
			this.AddFieldIndexEnumForElementName(typeof(ToppingFieldIndex), "ToppingEntity");
			this.AddElementFieldInfo("ToppingEntity", "Option", typeof(System.String), true, false, false, false,  (int)ToppingFieldIndex.Option, 1073741824, 0, 0);
			this.AddElementFieldInfo("ToppingEntity", "Price", typeof(System.Decimal), false, false, false, false,  (int)ToppingFieldIndex.Price, 0, 0, 0);
		}
	}
}