//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace View.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'PizzaTopping'.</summary>
	[Serializable]
	[DataContract]
	public partial class PizzaToppingView
	{
		/// <summary>Gets or sets the PizzaId field. Derived from Entity Model Field 'PizzaTopping.PizzaId (FK)'</summary>
		[DataMember]
		public System.Int32 PizzaId { get; set; }
		/// <summary>Gets or sets the Topping field. Derived from Entity Model Field 'PizzaTopping.Topping (FK)'</summary>
		[DataMember]
		public System.String Topping { get; set; }
	}

}




