//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace View.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Size'.</summary>
	[Serializable]
	[DataContract]
	public partial class SizeView
	{
		/// <summary>Gets or sets the Multiplier field. Derived from Entity Model Field 'Size.Multiplier'</summary>
		[DataMember]
		public System.Single Multiplier { get; set; }
		/// <summary>Gets or sets the Option field. Derived from Entity Model Field 'Size.Option'</summary>
		[DataMember]
		public System.String Option { get; set; }
	}

}




