//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace View.DtoClasses
{ 
	/// <summary> DTO class which is derived from the entity 'Topping'.</summary>
	[Serializable]
	[DataContract]
	public partial class ToppingView
	{
		/// <summary>Gets or sets the Option field. Derived from Entity Model Field 'Topping.Option'</summary>
		[DataMember]
		public System.String Option { get; set; }
		/// <summary>Gets or sets the Price field. Derived from Entity Model Field 'Topping.Price'</summary>
		[DataMember]
		public System.Decimal Price { get; set; }
	}

}




