//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro v5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;
using SD.LLBLGen.Pro.ORMSupportClasses;

namespace Restaurant.DatabaseSpecific
{
	/// <summary>Singleton implementation of the PersistenceInfoProvider. This class is the singleton wrapper through which the actual instance is retrieved.</summary>
	internal static class PersistenceInfoProviderSingleton
	{
		private static readonly IPersistenceInfoProvider _providerInstance = new PersistenceInfoProviderCore();

		/// <summary>Dummy static constructor to make sure threadsafe initialization is performed.</summary>
		static PersistenceInfoProviderSingleton() {	}

		/// <summary>Gets the singleton instance of the PersistenceInfoProviderCore</summary>
		/// <returns>Instance of the PersistenceInfoProvider.</returns>
		public static IPersistenceInfoProvider GetInstance() { return _providerInstance; }
	}

	/// <summary>Actual implementation of the PersistenceInfoProvider. Used by singleton wrapper.</summary>
	internal class PersistenceInfoProviderCore : PersistenceInfoProviderBase
	{
		/// <summary>Initializes a new instance of the <see cref="PersistenceInfoProviderCore"/> class.</summary>
		internal PersistenceInfoProviderCore()
		{
			Init();
		}

		/// <summary>Method which initializes the internal datastores with the structure of hierarchical types.</summary>
		private void Init()
		{
			this.InitClass();
			InitBaseEntityMappings();
			InitDoughEntityMappings();
			InitOrderEntityMappings();
			InitPizzaEntityMappings();
			InitPizzaToppingEntityMappings();
			InitSizeEntityMappings();
			InitToppingEntityMappings();
		}

		/// <summary>Inits BaseEntity's mappings</summary>
		private void InitBaseEntityMappings()
		{
			this.AddElementMapping("BaseEntity", @"postgres", @"public", "base", 2, 0);
			this.AddElementFieldMapping("BaseEntity", "Option", "option", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("BaseEntity", "Price", "price", false, "Money", 0, 0, 0, false, "", null, typeof(System.Decimal), 1);
		}

		/// <summary>Inits DoughEntity's mappings</summary>
		private void InitDoughEntityMappings()
		{
			this.AddElementMapping("DoughEntity", @"postgres", @"public", "dough", 2, 0);
			this.AddElementFieldMapping("DoughEntity", "Option", "option", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("DoughEntity", "Price", "price", false, "Money", 0, 0, 0, false, "", null, typeof(System.Decimal), 1);
		}

		/// <summary>Inits OrderEntity's mappings</summary>
		private void InitOrderEntityMappings()
		{
			this.AddElementMapping("OrderEntity", @"postgres", @"public", "order", 2, 0);
			this.AddElementFieldMapping("OrderEntity", "CustomerName", "customer_name", true, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("OrderEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.order_id_seq", null, typeof(System.Int32), 1);
		}

		/// <summary>Inits PizzaEntity's mappings</summary>
		private void InitPizzaEntityMappings()
		{
			this.AddElementMapping("PizzaEntity", @"postgres", @"public", "pizza", 6, 0);
			this.AddElementFieldMapping("PizzaEntity", "Base", "base", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("PizzaEntity", "Dough", "dough", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
			this.AddElementFieldMapping("PizzaEntity", "Id", "id", false, "Integer", 0, 10, 0, true, "public.pizza_id_seq", null, typeof(System.Int32), 2);
			this.AddElementFieldMapping("PizzaEntity", "OrderId", "order_id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 3);
			this.AddElementFieldMapping("PizzaEntity", "Price", "price", false, "Money", 0, 0, 0, false, "", null, typeof(System.Decimal), 4);
			this.AddElementFieldMapping("PizzaEntity", "Size", "size", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 5);
		}

		/// <summary>Inits PizzaToppingEntity's mappings</summary>
		private void InitPizzaToppingEntityMappings()
		{
			this.AddElementMapping("PizzaToppingEntity", @"postgres", @"public", "pizza_topping", 2, 0);
			this.AddElementFieldMapping("PizzaToppingEntity", "PizzaId", "pizza_id", false, "Integer", 0, 10, 0, false, "", null, typeof(System.Int32), 0);
			this.AddElementFieldMapping("PizzaToppingEntity", "Topping", "topping", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits SizeEntity's mappings</summary>
		private void InitSizeEntityMappings()
		{
			this.AddElementMapping("SizeEntity", @"postgres", @"public", "size", 2, 0);
			this.AddElementFieldMapping("SizeEntity", "Multiplier", "multiplier", false, "Real", 0, 24, 0, false, "", null, typeof(System.Single), 0);
			this.AddElementFieldMapping("SizeEntity", "Option", "option", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 1);
		}

		/// <summary>Inits ToppingEntity's mappings</summary>
		private void InitToppingEntityMappings()
		{
			this.AddElementMapping("ToppingEntity", @"postgres", @"public", "topping", 2, 0);
			this.AddElementFieldMapping("ToppingEntity", "Option", "option", false, "Text", 1073741824, 0, 0, false, "", null, typeof(System.String), 0);
			this.AddElementFieldMapping("ToppingEntity", "Price", "price", false, "Money", 0, 0, 0, false, "", null, typeof(System.Decimal), 1);
		}

	}
}
