//////////////////////////////////////////////////////////////
// <auto-generated>This code was generated by LLBLGen Pro 5.5.</auto-generated>
//////////////////////////////////////////////////////////////
// Code is generated on: 
// Code is generated using templates: SD.TemplateBindings.SharedTemplates
// Templates vendor: Solutions Design.
//////////////////////////////////////////////////////////////
using System;

namespace Restaurant
{


	/// <summary>Enum definition for all the entity types defined in this namespace. Used by the entityfields factory.</summary>
	public enum EntityType
	{
		///<summary>Base</summary>
		BaseEntity,
		///<summary>Dough</summary>
		DoughEntity,
		///<summary>Order</summary>
		OrderEntity,
		///<summary>Pizza</summary>
		PizzaEntity,
		///<summary>PizzaTopping</summary>
		PizzaToppingEntity,
		///<summary>Size</summary>
		SizeEntity,
		///<summary>Topping</summary>
		ToppingEntity
	}



	// __LLBLGENPRO_USER_CODE_REGION_START CustomUserConstants
	// __LLBLGENPRO_USER_CODE_REGION_END


}

